---
# Variables
- include_vars: jenkins/innomindstest/variables.yml


# Directory
- name: Jenkins jobs directory
  file:
    path: "{{ jenkins_jobs_dir }}/{{ jobName }}"
    state: directory
    owner: jenkins
#    sudo: yes
# Job configuration
- name: Jenkins build job configuration
  template:
    src: config.xml.j2
    dest: "{{ jenkins_jobs_dir }}/{{ jobName }}/config.xml"
#    become: True
  notify: Restart Jenkins
